name: '${project.name}'
version: '${project.version}'
authors: ${authors}
website: '${project.url}'
main: pl.craftserve.radiation.RadiationPlugin
api-version: '${apiVersion}'
description: Makes world radioactive
depend: ['WorldGuard']

commands:
  radiation:
    description: 'Set the safe-from-radiation zone.'
    aliases: ['radiacja']
    permission: 'craftserveradiation.safefromradiation'
    usage: '/radiation <safe/potion>'

permissions:
  craftserveradiation.*:
    description: 'Gives all possible permissions.'
    default: false
    children:
    - 'craftserveradiation.ad'
    - 'craftserveradiation.safefromradiation'
  craftserveradiation.ad:
    description: 'Gives access to print Craftserve advertisement.'
    default: op
  craftserveradiation.radiation:
    description: 'Gives access to the "/radiation" command.'
    default: op
